Dynamic connectivity problem
algorithms-club/algorithms-tatsiak pull request #2
Opened 2017-04-04 21:40 UTC by tatsiak

Created method count, method component and tests for them.

2017-04-05 20:20 UTC, PavelMelnyk commented
You should start working with new feature from `master` not from your last branch

if you just finish work on the old task, then your next steps are:
```
git checkout master //first go to master
git pull origin master // update it
git checkout -b my-new-bright-future // create a new branch and goes here
```
now you can work with new one in new branch

2017-04-05 20:20 UTC, pavlom0x requested changes

2017-04-05 20:20 UTC, pavlom0x commented on app/unionFind.js
> +         this._elements[b] = isNaN(this._elements[b]) ? b : this._elements[b];
it's better to choose one way to set elements
or `if` or `?`

2017-04-05 20:20 UTC, pavlom0x commented on app/unionFind.js
> +        return this._elements[a] === this._elements[b];
here some indentation issue

2017-04-05 20:20 UTC, pavlom0x commented on app/unionFind.js
> +     }
here some indentation issue

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> +
do you actually need this extra empty line?

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> + describe.only('#unionFind', function () {
forgot `only`
be careful, if you break something in the code, no one will see it

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> +
indentation in all test cases

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> +     it('should return true if number of components is 1', function () {
it should return number of components not `true` or `false`

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> +     it('should return true if elements are connected', function () {
you can make sub group of tests 
```
describe('#unionFind', function () {
    describe('#connect', function () {
        it(...);
    })
})
```

2017-04-05 20:20 UTC, PavelMelnyk commented on test/unionFind.spec.js
> +    it('should return component name', function () {
you already have this test above

2017-04-07 11:45 UTC, tatsiak commented on app/unionFind.js
> +        return this._elements[a] === this._elements[b];
sorry, I've tried to reformat code in sublime.... Now I'm going to use PyCharm

2017-04-07 11:47 UTC, tatsiak commented on test/unionFind.spec.js
> +
fixed

2017-04-07 11:47 UTC, tatsiak commented on app/unionFind.js
> +     }
fixed

2017-04-07 11:47 UTC, tatsiak commented on test/unionFind.spec.js
> +
fixed

2017-04-07 11:54 UTC, tatsiak commented on test/unionFind.spec.js
> +     it('should return true if elements are connected', function () {
oh, great idea
implemented it

2017-04-07 11:59 UTC, tatsiak commented on test/unionFind.spec.js
> + describe.only('#unionFind', function () {
ok, sure
it was used only for debug.

2017-04-07 12:00 UTC, tatsiak commented on test/unionFind.spec.js
> +    it('should return component name', function () {
second test is a bit more complicated
So i decided to left only the second one.

2017-04-07 12:03 UTC, tatsiak commented on test/unionFind.spec.js
> +     it('should return true if number of components is 1', function () {
fixed

2017-04-07 12:15 UTC, tatsiak commented on app/unionFind.js
> +         this._elements[b] = isNaN(this._elements[b]) ? b : this._elements[b];
in this case it was useful to use a ternary operator
Is there some rules about using only "if else" or only ternary operators?

2017-04-07 12:26 UTC, merged