implemented quick union weighted
algorithms-club/algorithms-tatsiak pull request #4
Opened 2017-04-27 20:03 UTC by tatsiak

Homework which I haven't done in time.

2017-05-03 18:03 UTC, pavlom0x requested changes

2017-05-03 18:03 UTC, PavelMelnyk commented on app/quickUnionWeighted.js
> +        if (this._size[parentA] > this._size[parentB]) {
You should connect smaller component to bigger
and you should have a test that checked it

2017-05-03 18:03 UTC, PavelMelnyk commented on test/quickUnionWeighted.spec.js
> +            componentName.should.be.eql(9);
it should not return `9`, it should return `1` or `3` depend on your implementation
method `uf.component` implement wrong

it should go from element to it parent until index and value equal each other
try to draw how it work on a piece of paper

2017-05-03 19:38 UTC, tatsiak commented on app/quickUnionWeighted.js
> +        if (this._size[parentA] > this._size[parentB]) {
fixed

2017-05-03 19:39 UTC, tatsiak commented on test/quickUnionWeighted.spec.js
> +            componentName.should.be.eql(9);
fixed

2017-05-04 05:58 UTC, pavlom0x approved these changes

2017-05-04 05:59 UTC, PavelMelnyk commented
you can merge it

2017-05-04 07:27 UTC, merged